server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Godot HTML5
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Go backend
    location /login {
        proxy_pass http://login:4000/login;
    }

    location /oidcc/ {
        proxy_pass http://login:4000/oidcc/;
    }

    location /me {
        proxy_pass http://login:4000/me;
    }
}